name: Build & Deploy Single JAR (App Service)

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Build Svelte (static)
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Copy into Spring static/
      - name: Copy UI into Spring static/
        run: |
          rm -rf SvelteAmazin/src/main/resources/static
          mkdir -p SvelteAmazin/src/main/resources/static
          cp -r frontend/build/* SvelteAmazin/src/main/resources/static/

      # Build JAR
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Package backend
        working-directory: SvelteAmazin
        run: ./mvnw -B -DskipTests package

      # Deploy to Azure App Service
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2DD3F47BC774F9897A7354F257AF202 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E820BC5CA6B04D95B692E24BFC648702 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2B5805A6F05448A88D9A10E8589FF78C }}

      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SYSC4806Project'
          slot-name: 'Production'
          package: 'SvelteAmazin/target/*.jar'
